//auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_CLOSE = 'LOGIN_CLOSE';
export const AUTENTICATE_USER = 'AUTENTICATE_USER';
export const AUTENTICATE_USER_ERROR = 'AUTENTICATE_USER_ERROR';



//app
export const ADD_PRODUCT_CART = 'ADD_PRODUCT_CART';
export const UPDATE_PRODUCT_CART = 'UPDATE_PRODUCT_CART';
export const UPDATE_PRODUCT_CART_REMOVE = 'UPDATE_PRODUCT_CART_REMOVE';
export const REMOVE_PRODUCT_CART = 'REMOVE_PRODUCT_CART';
export const UPDATE_PRICE_TOTAL = 'UPDATE_PRICE_TOTAL';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR';
export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAN_MESSAGE = 'CLEAN_MESSAGE';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const LIMPIAR_ALERTA = 'LIMPIAR_ALERTA';

export const CLEAN_STATE = 'CLEAN_STATE';
export const CLEAN_ALERT = 'CLEAN_ALERT';

